- name: Create redis directory
  file:
    path: /redis
    state: directory
    mode: '0755'

- name: Copy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "/redis/docker-compose.yml"

- name: Run docker
  community.general.docker_compose:
    project_src: /redis
    build: yes
