- name: increase memory capacity
  command: sysctl -w vm.max_map_count=262144

- name: Create elastic directory
  file:
    path: /elastic
    state: directory
    mode: '0755'

- name: Copy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "/elastic/docker-compose.yml"

- name: Run docker
  community.general.docker_compose:
    project_src: /elastic
    build: yes
