- name: Create gitlab directory
  file:
    path: /gitlab
    state: directory
    mode: '0755'

- name: Copy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "/gitlab/docker-compose.yml"

- name: Run docker
  community.general.docker_compose:
    project_src: /gitlab
    build: yes
